### ISSUE TITLE
Configuration per process ?

### ISSUE THREAD

**Issue by danielkcz** [mattpker/pm2-slack#4]
I am not familiar with PM2 plugin architecture, but is it possible to somehow enable this plugin only for a particular process? On our server there are some processed which are not production related so we don't care about those much.

**Comment by mattpker** [comment]
@kjhangiani mentioned he would also like this feature. PM2 does not have a built in way to enable this per app. This could be done in the code though since I know the name of the app for each alert. So we could so something like set a config option with an array of the app names you want it to be enabled on.

For a solution right now, you can run PM2 on separate Linux users. For example, you can create a Linux user for each app you have and then run PM2 for each user and only install pm2-slack on the users that you want it for. This will also allow you to have per app config options for which events to listen for. This method also has other benefits of securing an app to only a specific user so the app is contained with only that users permissions. 

I will research implementing this feature, if you or @kjhangiani have any ideas for how best to do this please let me know.

Thanks for the suggestion!

**Comment by danielkcz** [comment]
Yes, I think that something simple like configuration option with list of enabled apps could be more than enough. Perhaps provide both way like include & exclude and maybe with partial name matching so I can exclude all 'pm-' prefixed apps.

In case we would need a way different configuration (like a slack url) than your solution with more users is definitely good way to go, but it should be mentioned in docs.

**Comment by Kignuf** [comment]
Definitely +1 to this suggestion

**Comment by poohitan** [comment]
+1

**Comment by rmhall** [comment]
+1

**Comment by ma-zal** [comment]
See the pull request https://github.com/mattpker/pm2-slack/pull/22 and test it, please.

**Comment by mattpker** [comment]
Fixed by #22
