### ISSUE TITLE
Events not being fired

### ISSUE THREAD

**Issue by ghost** [mattpker/pm2-slack#6]
I have used it to monitor my apps. But the thing is that it is not properly emitting the events. Restarting an app doesn't emit restart event , instead, it emits two exit events. Anybody got an idea why it might be happening?

**Comment by mattpker** [comment]
Did you enable it to watch for the restart event?

`pm2 set pm2-slack:restart true`

**Comment by Ridermansb** [comment]
Same to me .. did not fire nothing ..

My configs ...

**slack_url** https://hooks.slack.com/....
**log** true
**error**  true
**restart** true
**exist**  true
**start**  true
**online** true
**stop**  true

**Comment by ghost** [comment]
Yeah , i figured out the problem. If you are manually testing from the terminal, the data. manually flag is on and it returns without invoking the service functions. Be careful with that return statement.
Well, you can also additionally add a flag in your config like log manually and make it and with the statement in data. manually if condition.

**Comment by mattpker** [comment]
How are you guys doing a restart? Like pm2 restart app or some full pm2 restart with service?

**Comment by mattpker** [comment]
Closing this issue as I have not heard back and I cannot duplicate.

**Comment by muke1908** [comment]
@mattpker, I am having the same issue. I am not getting any log stream to slack. Is there any way to check if pm2-slack is running or not?

**Comment by randommr3** [comment]
Hey,
I don't know if this is the correct way but I also didn't see any logs from pm2-slack until I did this:
Go to pm2-slack install folder, for me this was:

`cd ~/.pm2/modules/pm2-slack/node_modules/pm2-slack/`
Start pm2-slack as a pm2 service:
`pm2 start index.js --name=pm2-slack`

Now the logs started flooding in as per my `pm2 set pm2-slack:...` settings.

I also did `pm2 update` so that the service gets recognized as Module if you do `pm2 status`.

Hope this helps.
